### ISSUE TITLE
Text to speech for godot

### ISSUE THREAD

**Issue by ghost** [i-bardinov/Godot-GooglePlay-InApp-Review#1]
Hello sir please make a plugin for godot on text to speech. It will be helpfull for me

**Comment by i-bardinov** [comment]
Hi! You an find my TTS Plugin here: https://github.com/i-bardinov/Godot-Android-Text-to-Speech

**Comment by i-bardinov** [comment]
if you have any problems with plugin you can create an issue in tts repository
