### ISSUE TITLE
Build release version

### ISSUE THREAD

**Issue by SnailRabbids** [i-bardinov/Godot-GooglePlay-InApp-Review#5]
Hi, After steps in "Compiling the Plugin" in ...build/outputs/arr is only GodotGooglePlayInAppReview.1.0.1.debug.arr. How can I build the release version or they are same and I can use debug version in final version of my application?

**Comment by ghost** [comment]
> Hi, After steps in "Compiling the Plugin" in ...build/outputs/arr is only GodotGooglePlayInAppReview.1.0.1.debug.arr. How can I build the release version or they are same and I can use debug version in final version of my application?

You don't need to build a release version . Just rename it to "GodotGooglePlayInAppReview.1.0.1.release.aar".

**Comment by SnailRabbids** [comment]
@hani09876 thanks :)
