### ISSUE TITLE
License and Privacy Policy

### ISSUE THREAD

**Issue by SnailRabbids** [i-bardinov/Godot-GooglePlay-InApp-Review#7]
@i-bardinov 
Hello, I have few questions
1. Does the plugin collect any user’s data?
2. Do I need to add anything to my app's Privacy Policy if I use this plugin?
3. Do I need to add "License" file to my project if I use this plugin?

**Comment by i-bardinov** [comment]
Hello!
1. No it doesn’t
2. No you don’t
3. Up to you, I don’t insist

Вс, 21 мая 2023 г. в 17:55, SnailRabbids ***@***.***>:

**Comment by SnailRabbids** [comment]
@i-bardinov 
Thanks :)
